---
title: "First Knit"
author: "Jason A. Kirkendall"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I went to Highland High School and graduated in the distant future, the year 2000. Math is much easier to me than English. I could never tell you what poems mean. I did the best in Math and Sciences, eventually graduating with a BA in Chemistry from Cal State University, Channel Islands. I was a Secondary Educator for a private school for 5 years before becoming a lab tech for the Math department at AVC.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I use an old Macbook Pro to do all my work, but I am comfortable using windows as I have grown up with it. I would rate myself as a 5 on the spectrum of knowing computer stuff, but I imagine many people would rate me higher. At home I have a reliable fast connection to the internet where I enjoy streaming 4K content.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  My name is Jason and I am fine being called Jason, however I find that people that I know and trust will sometimes make their own affectionate nickname for me. I highly enjoy this. As long as it is not too embarrassing, I can be great by being called just about anything they come up with. Just don't call me late for dinner.
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  My desire is to be best used in the service to others. The area to serve that best fits my skill sets is in teaching Math/Science. My most recent greatest interests are playing guitar and studying speakers, crossovers, and hifi loudspeaker design.
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




